language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python openssl git python-qt4 rabbitmq-server

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
  - ./freejournal_cli.py install bitmessage

# command to run tests, e.g. python setup.py test
script:
  - coverage run --omit=*/python?.?/*,*/site-packages/*,*__init__*,test_* -m unittest discover unittests

after_success:
  coveralls
